trigger:

- main

pool:
  name: Default   # <-- use your self-hosted pool name, "Default" by default
 
steps:
- script: echo Hello from self-hosted Windows agent!
  displayName: 'Run a one-line script'

- powershell: |
    Write-Host "Running on Windows self-hosted agent"
    Write-Host "Machine name: $env:COMPUTERNAME"
    Write-Host "User: $env:USERNAME"
  displayName: 'Run PowerShell on Windows'
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifyBuildId: 'test'
    fortifyScanType: 'LocalScan'
